# Generated by Django 3.2.3 on 2021-07-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='smartphones')),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('color', models.CharField(choices=[('black', 'black'), ('red', 'red'), ('white', 'white')], default='black', max_length=20)),
                ('almacenamiento', models.CharField(choices=[('64', '64GB'), ('128', '128GB'), ('256', '256GB')], default='64', max_length=5)),
            ],
        ),
    ]
