# Generated by Django 3.2.3 on 2021-07-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smartphone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('red', 'red'), ('white', 'white'), ('blue', 'blue')], default='black', max_length=20),
        ),
    ]
